services:
  jenkins:
    image: jenkins/jenkins:2.471-jdk21
    ports:
      - "9991:8080"
      - "50000:50000"
    networks:
      - local-dev-network
    volumes:
      - ${HOST_JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  local-dev-network:
    external: true  # 이미 만들어진 네트워크 사용
